# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 410)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(7, 7, 7);\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: rgb(74, 74, 74);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(16, 16, 16);")
        self.centralwidget.setObjectName("centralwidget")
        self.btn_openO = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openO.setGeometry(QtCore.QRect(0, 100, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_openO.setFont(font)
        self.btn_openO.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.btn_openO.setObjectName("btn_openO")
        self.btn_closeO = QtWidgets.QPushButton(self.centralwidget)
        self.btn_closeO.setGeometry(QtCore.QRect(200, 100, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_closeO.setFont(font)
        self.btn_closeO.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.btn_closeO.setObjectName("btn_closeO")
        self.btn_regulateO = QtWidgets.QPushButton(self.centralwidget)
        self.btn_regulateO.setGeometry(QtCore.QRect(400, 100, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_regulateO.setFont(font)
        self.btn_regulateO.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.btn_regulateO.setObjectName("btn_regulateO")
        self.btn_openAr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openAr.setGeometry(QtCore.QRect(0, 310, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_openAr.setFont(font)
        self.btn_openAr.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.btn_openAr.setObjectName("btn_openAr")
        self.btn_closeAr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_closeAr.setGeometry(QtCore.QRect(200, 310, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_closeAr.setFont(font)
        self.btn_closeAr.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.btn_closeAr.setObjectName("btn_closeAr")
        self.btn_regulateAr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_regulateAr.setGeometry(QtCore.QRect(400, 310, 200, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_regulateAr.setFont(font)
        self.btn_regulateAr.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.btn_regulateAr.setObjectName("btn_regulateAr")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(0, 210, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label_2.setObjectName("label_2")
        self.label_realflowAr = QtWidgets.QLabel(self.centralwidget)
        self.label_realflowAr.setGeometry(QtCore.QRect(140, 220, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.label_realflowAr.setFont(font)
        self.label_realflowAr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_realflowAr.setObjectName("label_realflowAr")
        self.label_realflowO = QtWidgets.QLabel(self.centralwidget)
        self.label_realflowO.setGeometry(QtCore.QRect(140, 10, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.label_realflowO.setFont(font)
        self.label_realflowO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_realflowO.setObjectName("label_realflowO")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 150, 16, 20))
        self.label.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 150, 16, 20))
        self.label_3.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(575, 150, 16, 20))
        self.label_4.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(115, 50, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(301, 0, 298, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(415, 50, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(301, 210, 298, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.label_8.setObjectName("label_8")
        self.text_givenflowO = QtWidgets.QTextEdit(self.centralwidget)
        self.text_givenflowO.setGeometry(QtCore.QRect(430, 10, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_givenflowO.setFont(font)
        self.text_givenflowO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_givenflowO.setObjectName("text_givenflowO")
        self.text_givenflowO_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.text_givenflowO_2.setGeometry(QtCore.QRect(430, 230, 151, 71))
        self.text_givenflowO_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_givenflowO_2.setObjectName("text_givenflowO_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_openO.clicked.connect(self.click_open0) #функции нажатия на кнопки
        self.btn_openAr.clicked.connect(self.click_openAr)
        self.btn_closeO.clicked.connect(self.click_closeO)
        self.btn_closeAr.clicked.connect(self.click_closeAr)
        self.btn_regulateO.clicked.connect(self.click_regulateO)
        self.btn_regulateAr.clicked.connect(self.click_regulateAr)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MPC ONE"))
        self.btn_openO.setText(_translate("MainWindow", "Открыть O"))
        self.btn_closeO.setText(_translate("MainWindow", "Закрыть O"))
        self.btn_regulateO.setText(_translate("MainWindow", "Регулировать O"))
        self.btn_openAr.setText(_translate("MainWindow", "Открыть Ar"))
        self.btn_closeAr.setText(_translate("MainWindow", "Закрыть Ar"))
        self.btn_regulateAr.setText(_translate("MainWindow", "Регулировать Ar"))
        self.label_1.setText(_translate("MainWindow", "Поток Ar"))
        self.label_2.setText(_translate("MainWindow", "Поток O "))
        self.label_realflowAr.setText(_translate("MainWindow", "0.00"))
        self.label_realflowO.setText(_translate("MainWindow", "0.00"))
        self.label.setText(_translate("MainWindow", "2"))
        self.label_3.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "2"))
        self.label_6.setText(_translate("MainWindow", "Поток O"))
        self.label_7.setText(_translate("MainWindow", "2"))
        self.label_8.setText(_translate("MainWindow", "Поток Ar"))

    def click_open0(self):
        a = "010F00020101"
        print(a) #тыкаем rs

    def click_openAr(self):
        a = "020F00020101"
        print(a)
        
    def click_closeO(self):
        a = "010F00020102"
        print(a)
        
    def click_closeAr(self):
        a = "020F00020102"
        print(a)
        
    def click_regulateO(self):
        a = "010F00020100"
        print(a)

    def click_regulateAr(self):
        a = "120F00020100"
        print(a)

    def show_error(self, number): #вывод ошибки 
        error = QMessageBox()
        error.setWindowTitle("Ошибка")
        error.setText("Это еще не сделано")
        error.setIcon(QMessageBox.Warning)
        error.setStandardButtons(QMessageBox.Ok)
        error.exec()

    #def get_bit(self, text):
        #a = self.btn_openO.text()
        #print(a)
        #return a
    
    def write_number(self, number):
        print(number)
        #self.label_1.setText(self.lable_1.text()+ numer) что-то неправильное

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
